help('sum')
example('sum')
data()
cars
# install.packages('ggplot2')
# library(ggplot2)
installed.packages()
# update.packages('ggplot2')
# update.packages()
setwd('E:\\[학교폴더]\\[개별공부]\\Python Data Science\\[Data Internship Pre-edu]\\R Program 입문 - 데이터 통계분석')
